---
title: "Prédiction du sécrétome"
author: "CHARRIAT Florian"
date: "19 mai 2018"
output:
  html_document:
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
---

```{r knitr setup, include=FALSE,  eval=TRUE, echo=FALSE, warning=FALSE}
# knitr::opts_chunk$set(echo=TRUE, eval=TRUE, cache=TRUE, message=FALSE, warning=FALSE, comment="")

library(knitr)
options(width=300)
knitr::opts_chunk$set(
  fig.width = 10, 
  fig.height = 5, 
  fig.align = "center", 
  size = "tiny", 
  echo = TRUE, eval=TRUE, 
  warning = FALSE, message = FALSE, 
  results = TRUE, comment = "")
# knitr::asis_output("\\footnotesize")

```

<p style="text-align:justify";>Aprés avoir répcupéré les sequences protéiques des fichiers d'annotations, le script XXX est utilisé pour prédire le secretome de chaque assemblage. Ce scipt utilise plusieurs outil afin d'améliorer la fiabilité de la prediction.</p>


```{r Package, echo=FALSE}
if(!require("knitr"))
  {
  install.packages('knitr')
}
if(!require("DT"))
  {
  install.packages('DT')
  }
library('knitr')
library('DT')
```
